Add support for Puppet 8
opus-codium/puppet-ssh pull request #71
Opened 2023-06-16 08:09 UTC by smortex

2023-06-29 07:58 UTC, neomilium commented
Puppet 8 needs to be fixed before PR?

2023-06-29 07:59 UTC, neomilium requested changes
Code needs to be fixed to run with Puppet 8.

2023-06-29 19:57 UTC, smortex commented
We need to msync all modules. From my tests, this error is due to some old test libs that got fixed.  It happens for some but not all of our modules, and the new testing libs are not compatible with Puppet 6, so we will drop Puppet 6 support for all our modules.

I'll `msync update` soon, wanted to have codeowners merged to have more reviewers added automatically before doing it.

2023-07-04 06:58 UTC, neomilium approved these changes

2023-07-04 07:01 UTC, merged